repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake --in-place --remove-all-unused-imports --remove-unused-variables --
        language: system
        types: [ python ]
        pass_filenames: true

      - id: isort
        name: isort
        entry: isort --settings-file ./.isort.cfg --profile black --
        language: system
        types: [ python ]
        pass_filenames: true

      - id: black
        name: black
        entry: black --config pyproject.toml --
        language: system
        types: [python]
        pass_filenames: true

      - id: flake8
        name: flake8
        entry: flake8 --config .flake8 --
        language: system
        types: [python]
        pass_filenames: true
